// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdobftnqlikvafxzhkog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkb2JmdG5xbGlrdmFmeHpoa29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTQ3NzgsImV4cCI6MjA2NTQ5MDc3OH0.XWzastahcnq6yV1Pil-YjtmfxqN4n1pfob2JhpKzClw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);